import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ActiveSectionContextProvider from "@/components/ui/active-section-context";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ActiveSectionContextProvider>
          <main className="bg-gray-900">
            <Navbar />
            <div className="min-h-screen flex flex-col items-center py-32">
              {children}
            </div>
            <Footer />
          </main>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
